"""Tests for the AI build-fixer loop.

The security-critical case (test_rejects_crypto_diff_without_applying) proves the
guardrail holds when Claude returns something dangerous: a diff touching a protected
crypto path is screened out, the confirm gate is never reached, and nothing is
applied. The other cases cover the happy path, an explicit decline, and an
unparseable diff — none of which may crash the loop.

request_fix (the only network call) is monkeypatched throughout; no API is hit.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

from pqc_boot.config import Config
from pqc_boot.context import Context
from pqc_boot.ai import build_fixer

GIT = shutil.which("git")
needs_git = pytest.mark.skipif(GIT is None, reason="git required")


def _repo(tmp_path) -> Context:
    """A tiny git repo standing in for ctx.uboot_dir (= workspace/'u-boot')."""
    uboot = tmp_path / "u-boot"
    uboot.mkdir()
    subprocess.run([GIT, "init", "-q", str(uboot)], check=True)
    subprocess.run([GIT, "-C", str(uboot), "config", "user.email", "t@t"], check=True)
    subprocess.run([GIT, "-C", str(uboot), "config", "user.name", "t"], check=True)
    (uboot / "foo.c").write_text("int main(void)\n{\n    return 0;\n}\n")
    subprocess.run([GIT, "-C", str(uboot), "add", "-A"], check=True)
    subprocess.run([GIT, "-C", str(uboot), "commit", "-qm", "init"], check=True)
    return Context.create(Config(workspace=tmp_path))


def _good_diff(uboot: Path) -> str:
    """A valid, cleanly-applying diff for foo.c, generated by git itself (so there
    are no hand-rolled whitespace mismatches)."""
    foo = uboot / "foo.c"
    orig = foo.read_text()
    foo.write_text(orig.replace("return 0;", "return 0; /* FIXED */"))
    diff = subprocess.run([GIT, "-C", str(uboot), "diff"],
                          capture_output=True, text=True).stdout
    foo.write_text(orig)  # revert the worktree; the loop must apply the diff itself
    return diff


# A diff touching a protected crypto/verification path (substring rule catches ml-dsa).
_CRYPTO_DIFF = """\
diff --git a/lib/ml-dsa/mldsa-verify.c b/lib/ml-dsa/mldsa-verify.c
new file mode 100644
--- /dev/null
+++ b/lib/ml-dsa/mldsa-verify.c
@@ -0,0 +1 @@
+/* tampered */
"""


@needs_git
def test_applies_good_fix(tmp_path, monkeypatch):
    ctx = _repo(tmp_path)
    diff = _good_diff(ctx.uboot_dir)
    monkeypatch.setattr(build_fixer, "request_fix", lambda c, e, s: diff)

    def build_once():
        ok = "FIXED" in (ctx.uboot_dir / "foo.c").read_text()
        return ok, "" if ok else "error: still broken"

    ok = build_fixer.run_fix_loop(
        ctx, build_once=build_once, gather_context=lambda e: {},
        confirm=lambda d, s: True, first_error="error: broken",
    )
    assert ok is True
    assert "FIXED" in (ctx.uboot_dir / "foo.c").read_text()


@needs_git
def test_rejects_crypto_diff_without_applying(tmp_path, monkeypatch):
    """SECURITY: a diff touching a crypto/verify path is screened out, the confirm
    gate is never reached, and nothing is written to the tree."""
    ctx = _repo(tmp_path)
    monkeypatch.setattr(build_fixer, "request_fix", lambda c, e, s: _CRYPTO_DIFF)

    confirm_calls = {"n": 0}
    build_calls = {"n": 0}

    def confirm(d, s):
        confirm_calls["n"] += 1
        return True  # even a "yes" must not matter — screening happens first

    def build_once():
        build_calls["n"] += 1
        return True, ""

    ok = build_fixer.run_fix_loop(
        ctx, build_once=build_once, gather_context=lambda e: {},
        confirm=confirm, first_error="error: broken",
    )
    assert ok is False
    assert confirm_calls["n"] == 0, "confirm must never be reached for a rejected diff"
    assert build_calls["n"] == 0, "no rebuild should follow a rejected diff"
    # The protected file must not have been created in the tree.
    assert not (ctx.uboot_dir / "lib/ml-dsa/mldsa-verify.c").exists()


@needs_git
def test_decline_aborts_without_applying(tmp_path, monkeypatch):
    ctx = _repo(tmp_path)
    diff = _good_diff(ctx.uboot_dir)
    monkeypatch.setattr(build_fixer, "request_fix", lambda c, e, s: diff)

    ok = build_fixer.run_fix_loop(
        ctx, build_once=lambda: (True, ""), gather_context=lambda e: {},
        confirm=lambda d, s: False, first_error="error: broken",
    )
    assert ok is False
    assert "FIXED" not in (ctx.uboot_dir / "foo.c").read_text()


@needs_git
def test_unparseable_diff_does_not_crash(tmp_path, monkeypatch):
    """A diff git can't parse is discarded (DiffApplyError caught), not propagated."""
    ctx = _repo(tmp_path)
    monkeypatch.setattr(build_fixer, "request_fix", lambda c, e, s: "not a real diff")

    ok = build_fixer.run_fix_loop(
        ctx, build_once=lambda: (True, ""), gather_context=lambda e: {},
        confirm=lambda d, s: True, first_error="error: broken",
    )
    assert ok is False
